// Code generated by seekdb-go. DO NOT EDIT.
// CGo bindings for libseekdb.so C API.

//go:build cgo && (linux || darwin)

package seekdb

/*
#cgo LDFLAGS: -L${SRCDIR}/libseekdb -Wl,-rpath,${SRCDIR}/libseekdb -lseekdb
#include "libseekdb/seekdb.h"
#include <stdlib.h>
*/
import "C"
import (
	"fmt"
	"unsafe"
)

// seekdbOpen opens an embedded database.
func seekdbOpen(dbDir string) error {
	cDir := C.CString(dbDir)
	defer C.free(unsafe.Pointer(cDir))
	ret := C.seekdb_open(cDir)
	if ret != C.SEEKDB_SUCCESS {
		return lastError()
	}
	return nil
}

// seekdbOpenWithService opens an embedded database with network support.
// If port > 0, runs in server mode. If port <= 0, runs in pure embedded mode.
func seekdbOpenWithService(dbDir string, port int) error {
	cDir := C.CString(dbDir)
	defer C.free(unsafe.Pointer(cDir))
	ret := C.seekdb_open_with_service(cDir, C.int(port))
	if ret != C.SEEKDB_SUCCESS {
		return lastError()
	}
	return nil
}

// seekdbClose closes the embedded database.
func seekdbClose() {
	C.seekdb_close()
}

// SeekdbConn represents a native seekdb connection handle (via CGo).
type SeekdbConn struct {
	handle C.SeekdbHandle
}

// seekdbConnect creates a new connection to the embedded database.
func seekdbConnect(database string, autocommit bool) (*SeekdbConn, error) {
	var cHandle C.SeekdbHandle
	cDB := C.CString(database)
	defer C.free(unsafe.Pointer(cDB))
	cAuto := C.bool(autocommit)

	ret := C.seekdb_connect(&cHandle, cDB, cAuto)
	if ret != C.SEEKDB_SUCCESS {
		return nil, lastError()
	}
	return &SeekdbConn{handle: cHandle}, nil
}

// Close closes and frees the connection handle.
func (c *SeekdbConn) Close() {
	if c.handle != nil {
		C.seekdb_connect_close(c.handle)
		c.handle = nil
	}
}

// Query executes a SQL statement.
func (c *SeekdbConn) Query(sql string) (*SeekdbResult, error) {
	var cResult C.SeekdbResult
	cSQL := C.CString(sql)
	defer C.free(unsafe.Pointer(cSQL))

	ret := C.seekdb_query(c.handle, cSQL, &cResult)
	if ret != C.SEEKDB_SUCCESS {
		return nil, c.errorf("query failed")
	}
	return &SeekdbResult{result: cResult, conn: c}, nil
}

// Ping checks if the connection is alive.
func (c *SeekdbConn) Ping() error {
	ret := C.seekdb_ping(c.handle)
	if ret != C.SEEKDB_SUCCESS {
		return c.errorf("ping failed")
	}
	return nil
}

// Exec executes a SQL statement and returns affected rows.
func (c *SeekdbConn) Exec(sql string) (int64, error) {
	var cResult C.SeekdbResult
	cSQL := C.CString(sql)
	defer C.free(unsafe.Pointer(cSQL))

	ret := C.seekdb_query(c.handle, cSQL, &cResult)
	if ret != C.SEEKDB_SUCCESS {
		return 0, c.errorf("exec failed")
	}
	if cResult != nil {
		C.seekdb_result_free(cResult)
	}
	affected := C.seekdb_affected_rows(c.handle)
	return int64(affected), nil
}

// QueryWithParams executes a parameterized SQL query.
func (c *SeekdbConn) QueryWithParams(sql string, params []interface{}) (*SeekdbResult, error) {
	var cResult C.SeekdbResult
	cSQL := C.CString(sql)
	defer C.free(unsafe.Pointer(cSQL))

	binds, frees, err := buildBindings(params)
	if err != nil {
		return nil, err
	}
	defer func() {
		for _, f := range frees {
			f()
		}
	}()

	if len(binds) == 0 {
		ret := C.seekdb_query(c.handle, cSQL, &cResult)
		if ret != C.SEEKDB_SUCCESS {
			return nil, c.errorf("query failed")
		}
		return &SeekdbResult{result: cResult, conn: c}, nil
	}

	ret := C.seekdb_query_with_params(c.handle, cSQL, &cResult, (*C.SeekdbBind)(unsafe.Pointer(&binds[0])), C.uint(len(binds)))
	if ret != C.SEEKDB_SUCCESS {
		return nil, c.errorf("query with params failed")
	}
	return &SeekdbResult{result: cResult, conn: c}, nil
}

// ExecWithParams executes a parameterized SQL statement.
func (c *SeekdbConn) ExecWithParams(sql string, params []interface{}) (int64, error) {
	var cResult C.SeekdbResult
	cSQL := C.CString(sql)
	defer C.free(unsafe.Pointer(cSQL))

	binds, frees, err := buildBindings(params)
	if err != nil {
		return 0, err
	}
	defer func() {
		for _, f := range frees {
			f()
		}
	}()

	var ret C.int
	if len(binds) == 0 {
		ret = C.seekdb_query(c.handle, cSQL, &cResult)
	} else {
		ret = C.seekdb_query_with_params(c.handle, cSQL, &cResult, (*C.SeekdbBind)(unsafe.Pointer(&binds[0])), C.uint(len(binds)))
	}
	if ret != C.SEEKDB_SUCCESS {
		return 0, c.errorf("exec with params failed")
	}
	if cResult != nil {
		C.seekdb_result_free(cResult)
	}
	affected := C.seekdb_affected_rows(c.handle)
	return int64(affected), nil
}

// Begin starts a transaction.
func (c *SeekdbConn) Begin() error {
	ret := C.seekdb_begin(c.handle)
	if ret != C.SEEKDB_SUCCESS {
		return c.errorf("begin failed")
	}
	return nil
}

// Commit commits a transaction.
func (c *SeekdbConn) Commit() error {
	ret := C.seekdb_commit(c.handle)
	if ret != C.SEEKDB_SUCCESS {
		return c.errorf("commit failed")
	}
	return nil
}

// Rollback rolls back a transaction.
func (c *SeekdbConn) Rollback() error {
	ret := C.seekdb_rollback(c.handle)
	if ret != C.SEEKDB_SUCCESS {
		return c.errorf("rollback failed")
	}
	return nil
}

// SetAutocommit sets autocommit mode.
func (c *SeekdbConn) SetAutocommit(mode bool) error {
	ret := C.seekdb_autocommit(c.handle, C.bool(mode))
	if ret != C.SEEKDB_SUCCESS {
		return c.errorf("autocommit failed")
	}
	return nil
}

// SelectDB switches to a different database.
func (c *SeekdbConn) SelectDB(db string) error {
	cDB := C.CString(db)
	defer C.free(unsafe.Pointer(cDB))
	ret := C.seekdb_select_db(c.handle, cDB)
	if ret != C.SEEKDB_SUCCESS {
		return c.errorf("select_db failed")
	}
	return nil
}

func (c *SeekdbConn) errorf(format string, args ...interface{}) error {
	msg := C.seekdb_error(c.handle)
	if msg != nil {
		format += ": %s"
		args = append(args, C.GoString(msg))
	}
	return fmt.Errorf(format, args...)
}

// SeekdbResult wraps a C result handle.
type SeekdbResult struct {
	result C.SeekdbResult
	conn   *SeekdbConn
}

// NumRows returns the number of rows in the result.
func (r *SeekdbResult) NumRows() int64 {
	if r.result == nil {
		return 0
	}
	return int64(C.seekdb_num_rows(r.result))
}

// NumFields returns the number of columns.
func (r *SeekdbResult) NumFields() int {
	if r.result == nil {
		return 0
	}
	return int(C.seekdb_num_fields(r.result))
}

// ColumnNames returns all column names.
func (r *SeekdbResult) ColumnNames() ([]string, error) {
	if r.result == nil {
		return nil, nil
	}
	var names **C.char
	var count C.int32_t
	ret := C.seekdb_result_get_all_column_names_alloc(r.result, &names, &count)
	if ret != C.SEEKDB_SUCCESS {
		return nil, fmt.Errorf("failed to get column names")
	}
	defer C.seekdb_free_column_names(names, count)

	result := make([]string, int(count))
	slice := unsafe.Slice(names, int(count))
	for i := range slice {
		result[i] = C.GoString(slice[i])
	}
	return result, nil
}

// FetchAll fetches all rows as [][]string.
func (r *SeekdbResult) FetchAll() ([][]string, error) {
	if r.result == nil {
		return nil, nil
	}
	numRows := int64(C.seekdb_num_rows(r.result))
	numCols := int(C.seekdb_num_fields(r.result))

	rows := make([][]string, numRows)
	for i := 0; i < int(numRows); i++ {
		row := C.seekdb_fetch_row(r.result)
		if row == nil {
			break
		}
		cols := make([]string, numCols)
		for j := 0; j < numCols; j++ {
			if C.seekdb_row_is_null(row, C.int32_t(j)) {
				cols[j] = ""
				continue
			}
			strLen := C.seekdb_row_get_string_len(row, C.int32_t(j))
			if strLen == C.size_t(^uint(0)) {
				cols[j] = ""
				continue
			}
			buf := C.malloc(strLen + 1)
			defer C.free(buf)
			ret := C.seekdb_row_get_string(row, C.int32_t(j), (*C.char)(buf), strLen+1)
			if ret != C.SEEKDB_SUCCESS {
				cols[j] = ""
			} else {
				cols[j] = C.GoStringN((*C.char)(buf), C.int(strLen))
			}
		}
		rows[i] = cols
	}
	return rows, nil
}

// Free frees the result.
func (r *SeekdbResult) Free() {
	if r.result != nil {
		C.seekdb_result_free(r.result)
		r.result = nil
	}
}

// buildBindings converts Go params to C SeekdbBind structures.
func buildBindings(params []interface{}) ([]C.SeekdbBind, []func(), error) {
	if len(params) == 0 {
		return nil, nil, nil
	}

	binds := make([]C.SeekdbBind, len(params))
	frees := make([]func(), 0, len(params))

	for i, param := range params {
		var b C.SeekdbBind
		switch v := param.(type) {
		case nil:
			b.buffer_type = C.SEEKDB_TYPE_NULL
		case string:
			cstr := C.CString(v)
			frees = append(frees, func() { C.free(unsafe.Pointer(cstr)) })
			b.buffer_type = C.SEEKDB_TYPE_STRING
			b.buffer = unsafe.Pointer(cstr)
			b.buffer_length = C.ulong(len(v))
		case int:
			val := C.int64_t(v)
			ptr := (*C.int64_t)(C.malloc(C.sizeof_int64_t))
			frees = append(frees, func() { C.free(unsafe.Pointer(ptr)) })
			*ptr = val
			b.buffer_type = C.SEEKDB_TYPE_LONGLONG
			b.buffer = unsafe.Pointer(ptr)
			b.buffer_length = C.ulong(C.sizeof_int64_t)
		case int64:
			ptr := (*C.int64_t)(C.malloc(C.sizeof_int64_t))
			frees = append(frees, func() { C.free(unsafe.Pointer(ptr)) })
			*ptr = C.int64_t(v)
			b.buffer_type = C.SEEKDB_TYPE_LONGLONG
			b.buffer = unsafe.Pointer(ptr)
			b.buffer_length = C.ulong(C.sizeof_int64_t)
		case float64:
			ptr := (*C.double)(C.malloc(C.sizeof_double))
			frees = append(frees, func() { C.free(unsafe.Pointer(ptr)) })
			*ptr = C.double(v)
			b.buffer_type = C.SEEKDB_TYPE_DOUBLE
			b.buffer = unsafe.Pointer(ptr)
			b.buffer_length = C.ulong(C.sizeof_double)
		case float32:
			ptr := (*C.double)(C.malloc(C.sizeof_double))
			frees = append(frees, func() { C.free(unsafe.Pointer(ptr)) })
			*ptr = C.double(v)
			b.buffer_type = C.SEEKDB_TYPE_DOUBLE
			b.buffer = unsafe.Pointer(ptr)
			b.buffer_length = C.ulong(C.sizeof_double)
		case bool:
			val := C.bool(v)
			ptr := (*C.bool)(C.malloc(1))
			frees = append(frees, func() { C.free(unsafe.Pointer(ptr)) })
			*ptr = val
			b.buffer_type = C.SEEKDB_TYPE_TINY
			b.buffer = unsafe.Pointer(ptr)
			b.buffer_length = 1
		case []byte:
			buf := C.CBytes(v)
			frees = append(frees, func() { C.free(buf) })
			b.buffer_type = C.SEEKDB_TYPE_BLOB
			b.buffer = buf
			b.buffer_length = C.ulong(len(v))
		case []float32:
			// Vector: encode as JSON array string
			json := float32SliceToJSON(v)
			cstr := C.CString(json)
			frees = append(frees, func() { C.free(unsafe.Pointer(cstr)) })
			b.buffer_type = C.SEEKDB_TYPE_VECTOR
			b.buffer = unsafe.Pointer(cstr)
			b.buffer_length = C.ulong(len(json))
		default:
			return nil, nil, fmt.Errorf("unsupported parameter type %T for param %d", param, i)
		}
		binds[i] = b
	}
	return binds, frees, nil
}

// float32SliceToJSON converts a []float32 to a JSON array string like "[0.1,0.2,0.3]".
func float32SliceToJSON(vs []float32) string {
	s := "["
	for i, v := range vs {
		if i > 0 {
			s += ","
		}
		s += fmt.Sprintf("%g", v)
	}
	s += "]"
	return s
}

// lastError returns the last thread-local error as a Go error.
func lastError() error {
	msg := C.seekdb_last_error()
	if msg != nil {
		return fmt.Errorf("seekdb error: %s", C.GoString(msg))
	}
	code := C.seekdb_last_error_code()
	return fmt.Errorf("seekdb error code: %d", int(code))
}
